language: rust
cache: cargo

rust:
  - 1.17.0
  - stable
  - beta
  - nightly

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export EXTRA_FEATURES=unstable export CARGO_TEST_EXTRA="--all"; fi

script:
  - cargo build --verbose --features="all ${EXTRA_FEATURES}"
  - RUST_BACKTRACE=1 cargo test --verbose --features="all ${EXTRA_FEATURES}" ${CARGO_TEST_EXTRA}

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
