language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly
  - 1.17.0 # Oldest supported version. Keep in sync with README.md.

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export EXTRA_FEATURES=unstable; fi

script:
  - cargo build --verbose --features="all ${EXTRA_FEATURES}"
  - RUST_BACKTRACE=1 cargo test --all --verbose --features="all ${EXTRA_FEATURES}"

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
