[package]
name = "sccache"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
clap = "2.3.0"
env_logger = "0.3.3"
fern = "0.3.5"
filetime = "0.1"
libc = "0.2.10"
log = "0.3.6"
mio = "0.5"
number_prefix = "0.2.5"
protobuf = "1.0.18"
retry = "0.4.0"
sha1 = "0.1.1"
tempdir = "0.3.4"
time = "0.1.35"
winapi = "0.2"
kernel32-sys = "0.2.2"
zip = { version = "0.1", default-features = false }

[dependencies.rusoto]
features = ["s3"]
git = "https://github.com/rusoto/rusoto"
branch = "feature_mutex_credentials"

[profile.release]
debug = true
