[package]
name = "sccache"
version = "0.1.1-pre"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "Apache-2.0"
description = "Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."
repository = "https://github.com/mozilla/sccache/"


[dependencies]
app_dirs = "1.1.1"
chrono = "0.2.25"
clap = "2.3.0"
env_logger = "0.3.3"
error-chain = { version = "0.7.2", default-features = false }
fern = "0.3.5"
filetime = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
libc = "0.2.10"
local-encoding = "0.2.0"
log = "0.3.6"
lru-disk-cache = { path = "lru-disk-cache" }
number_prefix = "0.2.5"
protobuf = "1.0.18"
regex = "0.1.65"
retry = "0.4.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3"
serde_json = "0.8.0"
sha1 = "0.2.0"
tempdir = "0.3.4"
time = "0.1.35"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-process = "0.1"
uuid = { version = "0.3.1", features = ["v4"] }
which = "0.2.1"
zip = { version = "0.1", default-features = false }

[target.'cfg(unix)'.dependencies]
daemonize = "0.2.3"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
named_pipe = "0.2.2"
winapi = "0.2"

[features]
default = []
# Enable features that require unstable features of Nightly Rust.
unstable = []

[profile.release]
debug = true

[workspace]
