[package]
name = "sccache"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
app_dirs = "1.1.1"
chrono = "0.2.25"
clap = "2.3.0"
env_logger = "0.3.3"
fern = "0.3.5"
filetime = "0.1"
futures = "0.1"
hyper = { version = "0.9.10", default-features = false }
libc = "0.2.10"
local-encoding = "0.2.0"
log = "0.3.6"
mio = "0.5"
number_prefix = "0.2.5"
protobuf = "1.0.18"
regex = "0.1.65"
retry = "0.4.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3"
rust-swiftclient = { git = "https://github.com/leth/rust-swiftclient.git" }
serde_json = "0.8.0"
sha1 = "0.2.0"
tempdir = "0.3.4"
time = "0.1.35"
which = "0.2.1"
winapi = "0.2"
kernel32-sys = "0.2.2"
zip = { version = "0.1", default-features = false }

[target.'cfg(unix)'.dependencies]
daemonize = "0.2.3"

[profile.release]
debug = true
