name: ci
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-16.04]
        kind: ['test_debug']
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Install rust
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: "1.43.0"
          components: clippy rustfmt

      - name: check formatting
        run: cargo fmt -- --check

      - name: build and test
        run: cargo test --locked --all-targets

     # TODO
     # - name: clippy
     #   run: cargo clippy --locked --all-target
